### ISSUE TITLE
Offline Use

### ISSUE THREAD

**Issue by minoush82** [RYOSKATE/PLIVET#307]
For offline use, you specify:
1. Download this repository.
2. Open `docs/index.html` by a modern browser.

I downloaded the repo, but there is no docs folder. There is however a `src` folder with an `index.html` file. Opening this file yields the error "Error: Could not establish connection. Receiving end does not exist.".

Could you please let me know how I use PLIVET offline?

**Comment by RYOSKATE** [comment]
@minoush82 
Sorry, the README has not been updated.
Please switch to the `gh-pages` branch (https://github.com/RYOSKATE/PLIVET/tree/gh-pages) and download it from there.

**Comment by minoush82** [comment]
Many thanks for your prompt reply :-)
